// Extracto de lib/staticData.js (solo lo que usa el login)

export const configByRole = {
  2: {
    userType: "CT",
    localUserType: "CT",
    appId: 6,
    mainRoute: "coordinador", // tkr
    routes: [
      "asignar-servicio",
      "consulta-programada",
      "consultas",
      "interconsulta",
      "pqrs",
      "notificaciones",
      "entidades",
      "especialidades",
      "usuarios",
      "disponibilidad",
      "faqs",
    ],
  },
  3: {
    userType: "P",
    localUserType: "P",
    appId: 1,
    mainRoute: "paciente",
    routes: [
      "citas",
      "consultas",
      "directorio",
      "grupo-medico",
      "documentos",
      "perfil",
      "familia",
      "referidos",
      "suscripciones",
      "faqs",
    ],
  },
  4: {
    userType: "M",
    localUserType: "M",
    appId: 2,
    mainRoute: "profesional",
    routes: [
      "consultas",
      "disponibilidad",
      "referencias",
      "pagos",
      "interconsulta",
      "documentos",
      "perfil",
      "faqs",
    ],
  },
  7: {
    userType: "E",
    localUserType: "AC",
    appId: 3,
    mainRoute: "aliado", // coordinador
    routes: [
      "consulta-programada",
      "consulta-inmediata",
      "interconsulta",
      "asignar-servicio",
      "consultas",
      "usuarios",
      // "documentos",
      "disponibilidad",
      "servicios",
      "perfil",
      "faqs",

      // *just for sead-medica
      "servicios-pendientes",
    ],
  },
  8: {
    userType: "E",
    localUserType: "AA",
    appId: 4,
    mainRoute: "aliado", // administrador
    routes: [
      "directorio",
      "documentos",
      "documentos-generales",
      "membresia",
      "disponibilidad",
      "perfil",
      "faqs",
    ],
  },
  9: {
    userType: "C",
    localUserType: "C",
    appId: 5,
    mainRoute: "corredor",
    routes: [
      "consulta-programada",
      "consulta-inmediata",
      "asignar-servicio",
      "consultas",
      "usuarios",
      "perfil",
      "faqs",
    ],
  },
  11: {
    userType: "CR",
    localUserType: "CR",
    appId: 7,
    mainRoute: "coordinador-riesgo",
    routes: [
      "cohorte",
      "consultas",
      "notificaciones",
      "pqrs",
      "faqs",
      "solicitud-citas",
    ],
  },
  12: {
    userType: "CM",
    localUserType: "CM",
    appId: 8,
    mainRoute: "coordinador-medico",
    routes: ["hc", "cuestionarios", "faqs"],
  },
};

export const idTypes = (countryId = 1) => {
  return [
    {
      id: -3,
      value: -3,
      title: "Licencia de Conducción",
      code: "LC",
      wompiCode: "OTHER",
      countryId: 3,
    },
    {
      id: -2,
      value: -2,
      title: "Instituto Nacional Electoral",
      code: "INE",
      wompiCode: "OTHER",
      countryId: 3,
    },
    {
      id: -1,
      value: -1,
      title: "Clave Única de Registro de Población",
      code: "CURP",
      wompiCode: "OTHER",
      countryId: 3,
    },
    {
      id: 4,
      value: 4,
      title: "Cédula de Ciudadanía",
      code: "CC",
      wompiCode: "CC",
      epaycoCode: "CC",
      countryId: 1,
    },
    {
      id: 6,
      value: 6,
      title: "Cédula de Extranjería",
      code: "CE",
      wompiCode: "CE",
      epaycoCode: "CE",
      countryId: 1,
    },
    {
      id: 1,
      value: 1,
      title: "Número Único de Identificación Personal",
      code: "NUIP",
      wompiCode: "DNI",
      epaycoCode: "DNI",
      countryId: 1,
    },
    {
      id: 5,
      value: 5,
      title: "Pasaporte",
      code: "PA",
      wompiCode: "PP",
      epaycoCode: "PPN",
      countryId: 1,
    },
    {
      id: 2,
      value: 2,
      title: "Registro Civil",
      code: "RC",
      wompiCode: "RG",
      countryId: 1,
    },
    {
      id: 3,
      value: 3,
      title: "Tarjeta de Identidad",
      code: "TI",
      wompiCode: "TI",
      epaycoCode: "TI",
      countryId: 1,
    },
    {
      id: 7,
      value: 7,
      title: "Número de Identificación Tributaria",
      code: "NIT",
      wompiCode: "NIT",
      epaycoCode: "NIT",
      countryId: 1,
    },
    {
      id: 8,
      value: 8,
      title: "Permiso por Protección Temporal",
      code: "PPT",
      wompiCode: "OTHER",
      countryId: 1,
    },
    {
      id: 9,
      value: 9,
      title: "Permiso Especial de Permanencia",
      code: "PEP",
      wompiCode: "OTHER",
      countryId: 1,
    },
  ]
    .filter((item) => item.countryId === countryId)
    .sort((a, b) => a.title.localeCompare(b.title));
};
